name: .NET CD - Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish R6ReadRecFile.CLI -c Release -o ./publish

      - name: Package Release Files (ZIP)
        run: zip -r release.zip ./publish

      - name: Package Release Files (TAR.GZ)
        run: tar -czf release.tar.gz ./publish

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.4
          name: Release v0.1.4
          body: "Automatic release from main branch."
          files: |
            release.zip
            release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
