name: .NET CD - Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Linux
        run: |
          dotnet publish R6ReadRecFile.CLI -c Release -r linux-x64 --self-contained true -o ./publish/linux
          zip -r release-linux.zip ./publish/linux
          tar -czf release-linux.tar.gz -C ./publish linux

      - name: Publish Windows
        run: |
          dotnet publish R6ReadRecFile.CLI -c Release -r win-x64 --self-contained true -o ./publish/windows
          zip -r release-windows.zip ./publish/windows
          tar -czf release-windows.tar.gz -C ./publish windows

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.4
          name: Release v0.1.4
          body: "Automatic release from main branch."
          files: |
            release-linux.zip
            release-linux.tar.gz
            release-windows.zip
            release-windows.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
