name: .NET CD - Release

on:
  push:
    branches:
      - main

jobs:
  build-release:
    name: Build Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish R6ReadRecFile.CLI -c Release -o ./publish

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0 
          name: Release v0.1.0
          body: "Release créée manuellement."
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
